- name: Set up for cakephp
  hosts: all
  become: yes
  # gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install remi repository
      yum:
        name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
        state: present

    - name: Install epel repository
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install webtatic repository
      yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        state: present

    - name: Install php-fpm and deps
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: remi,epel,webtatic
      with_items:
      - php70w
      - php70w-fpm
      - php70w-enchant
      - php70w-mbstring
      - php70w-mysql
      - php70w-mcrypt
      - php70w-opcache
      - php70w-xml

    - name: Install apache
      yum:
        name: httpd
        state: latest

    - name: Start apache and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install mysql
      yum:
        name: "{{ item }}"
        enablerepo: remi,epel
        state: installed
        with_items:
         - mysql-server
         - MySQL-python
        notify:
          - start mysql

    - name: Make phpmyadmin Directory
      file:
        path: /var/www/phpmyadmin
        state: directory

    - name: Get phpmyadmin and unarchive
      unarchive:
        src: https://files.phpmyadmin.net/phpMyAdmin/4.7.2/phpMyAdmin-4.7.2-all-languages.tar.gz
        dest: /var/www/phpmyadmin
        remote_src: True

    - name: Move phpmyadmin
      command: mv /var/www/phpmyadmin/phpMyAdmin-4.7.2-all-languages/* /var/www/phpmyadmin

  handlers:
    - name: Auto restart apache
      service:
        name: httpd
        state: restarted
        enabled: yes
    - name: start mysql
      service:
        name: mysqld
        state: started
        enabled: yes
