- name: Set up for cakephp
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install remi repository
      yum:
        name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
        state: present

    - name: Install epel repository
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install webtatic repository
      yum:
        name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
        state: present

    - name: Install php-fpm and deps extensions
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: remi,epel,webtatic
      with_items:
      - php70w
      - php70w-fpm
      - php70w-enchant
      - php70w-mbstring
      - php70w-mysql
      - php70w-mcrypt
      - php70w-opcache
      - php70w-xml
      - php70w-intl.x86_64

    - name: Install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
      args:
        creates: /usr/bin/composer.phar

    - name: Move composer.phar to composer
      command: mv /usr/bin/composer.phar /usr/bin/composer
      args:
        creates: /usr/bin/composer

    - name: Install apache
      yum:
        name: httpd
        state: latest

    - name: Set web root permission
      file:
        path: /var/www/html
        owner: apache
        group: apache
        recurse: true

    - name: Start apache and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install mariadb
      yum:
        name: "{{ item }}"
        enablerepo: remi,epel
        state: installed
      with_items:
        - mariadb
        - mariadb-server
        - MySQL-python

    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create DB "my_database"
      mysql_db:
        name: my_database
        state: present

    - name: Set root user password
      mysql_user:
        name: root
        password: root
        host: localhost
        state: present

    - name: Make phpmyadmin Directory
      file:
        path: /var/www/phpmyadmin
        state: directory

    - name: Get phpmyadmin and unarchive
      unarchive:
        src: https://files.phpmyadmin.net/phpMyAdmin/4.7.2/phpMyAdmin-4.7.2-all-languages.tar.gz
        dest: /var/www/phpmyadmin
        remote_src: True

    - name: Move phpmyadmin
      shell: mv /var/www/phpmyadmin/phpMyAdmin-4.7.2-all-languages/* /var/www/phpmyadmin

    - name: Make symbolic link
      shell: ln -fs /vagrant/public/ /var/www/app
    
    - name: Set virtual host for phpmyadmin
      template:
        src: ./templates/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
        owner: apache
        group: apache
        mode: 0755

    - name: Auto restart apache
      service:
        name: httpd
        state: restarted
        enabled: yes
